
# branches to build
branches:
  # whitelist
  only:
    - etp

skip_commits:
  message: /\[skip ci\]|\[ci skip\]|\[skip appveyor\]|\[ci appveyor\]/
  files:
    - .travis*
    - '*.md'

# clone directory
clone_folder: c:\projects\fesapiEnv\fesapi

# Build worker image (VM template)
image:
  - Visual Studio 2013
  - Visual Studio 2015
  #- Visual Studio 2017

configuration: 
  - Release
  #- Debug

platform:
  - x64

environment:
  matrix:
    - HDF5_STATE: STATIC 
    - HDF5_STATE: DYNAMIC

init:
  - echo %platform%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%platform%"=="x64" (set TARGET_PLATFORM= Win64)

build:
  parallel: true
  verbosity: minimal

for:
# VS2013 + dynamic hdf5
  -
    matrix:
      only:
        - image: Visual Studio 2013
          HDF5_STATE: DYNAMIC
    init:
      - set GENERATOR="Visual Studio 12 2013%TARGET_PLATFORM%"
      - echo %GENERATOR%
    install:
      - mkdir C:\projects\fesapiEnv\dependencies
      - cd C:\projects\fesapiEnv\dependencies
      
      - appveyor DownloadFile https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.18/bin/windows/noszip/hdf5-1.8.18-win64-vs2013-noszip.zip
      - 7z x hdf5-1.8.18-win64-vs2013-noszip.zip -oC:\projects\fesapiEnv\dependencies > nul 
      - msiexec.exe /i "C:\projects\fesapiEnv\dependencies\hdf5\HDF5-1.8.18-win64.msi" /qn INSTALL_ROOT=C:\projects\fesapiEnv\dependencies\hdf5-1.8.18-win64-vs2013-noszip
      
      - appveyor DownloadFile https://github.com/F2I-Consulting/Minizip/releases/download/1.1/minizip-1.1-win64-vs2013-static.zip
      - 7z x minizip-1.1-win64-vs2013-static.zip -oC:\projects\fesapiEnv\dependencies > nul
      - cd ..      
    build_script:
      - mkdir build
      - cd build
      - cmake --version
      - cmake -Wno-dev -Wno-deprecated -G %GENERATOR% ../fesapi
            -DHDF5_USE_STATIC_LIBRARIES:BOOL=OFF  
            -DHDF5_ROOT=C:\projects\fesapiEnv\dependencies\hdf5-1.8.18-win64-vs2013-noszip        
            -DCMAKE_PREFIX_PATH=c:/projects/fesapiEnv/dependencies/minizip-1.1-win64-vs2013-static 
      - cmake --build . --config "%CONFIGURATION%"
# VS2013 + static hdf5
  - 
    matrix:
      only:
        - image: Visual Studio 2013
          HDF5_STATE: STATIC 
    init:
      - set GENERATOR="Visual Studio 12 2013%TARGET_PLATFORM%"
      - echo %GENERATOR%
    install:
      - mkdir C:\projects\fesapiEnv\dependencies
      - cd C:\projects\fesapiEnv\dependencies
      
      - appveyor DownloadFile https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.18/bin/windows/noszip/hdf5-1.8.18-win64-vs2013-noszip.zip
      - 7z x hdf5-1.8.18-win64-vs2013-noszip.zip -oC:\projects\fesapiEnv\dependencies > nul 
      - msiexec.exe /i "C:\projects\fesapiEnv\dependencies\hdf5\HDF5-1.8.18-win64.msi" /qn INSTALL_ROOT=C:\projects\fesapiEnv\dependencies\hdf5-1.8.18-win64-vs2013-noszip
      
      - appveyor DownloadFile https://github.com/F2I-Consulting/Minizip/releases/download/1.1/minizip-1.1-win64-vs2013-static.zip
      - 7z x minizip-1.1-win64-vs2013-static.zip -oC:\projects\fesapiEnv\dependencies > nul
      - cd ..      
    build_script:
      - mkdir build
      - cd build
      - cmake --version
      - cmake -Wno-dev -Wno-deprecated -G %GENERATOR% ../fesapi
            -DHDF5_USE_STATIC_LIBRARIES:BOOL=ON 
            -DHDF5_ROOT=C:\projects\fesapiEnv\dependencies\hdf5-1.8.18-win64-vs2013-noszip        
            -DCMAKE_PREFIX_PATH=c:/projects/fesapiEnv/dependencies/minizip-1.1-win64-vs2013-static 
      - cmake --build . --config "%CONFIGURATION%"      
  # VS2015 + dynamic hdf5
  -
    matrix:
      only:
        - image: Visual Studio 2015  
          HDF5_STATE: DYNAMIC
    init:
      - set GENERATOR="Visual Studio 14 2015%TARGET_PLATFORM%"
      - echo %GENERATOR%
    install:
      - mkdir C:\projects\fesapiEnv\dependencies
      - cd C:\projects\fesapiEnv\dependencies
      
      - appveyor DownloadFile https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.18/bin/windows/noszip/extra/hdf5-1.8.18-win64-vs2015-noszip.zip
      - 7z x hdf5-1.8.18-win64-vs2015-noszip.zip -oC:\projects\fesapiEnv\dependencies > nul 
      - msiexec.exe /i "C:\projects\fesapiEnv\dependencies\hdf5\HDF5-1.8.18-win64.msi" /qn INSTALL_ROOT=C:\projects\fesapiEnv\dependencies\hdf5-1.8.18-win64-vs2015-noszip
      
      - appveyor DownloadFile https://github.com/F2I-Consulting/Minizip/releases/download/1.1/minizip-1.1-win64-vs2015-static.zip
      - 7z x minizip-1.1-win64-vs2015-static.zip -oC:\projects\fesapiEnv\dependencies > nul
      - cd ..    
    build_script:
      - mkdir build
      - cd build
      - cmake --version
      - cmake -Wno-dev -Wno-deprecated -G %GENERATOR% ../fesapi
            -DHDF5_USE_STATIC_LIBRARIES:BOOL=OFF  
            -DHDF5_ROOT=C:\projects\fesapiEnv\dependencies\hdf5-1.8.18-win64-vs2015-noszip          
            -DCMAKE_PREFIX_PATH=c:/projects/fesapiEnv/dependencies/minizip-1.1-win64-vs2015-static 
      - cmake --build . --config "%CONFIGURATION%"
  # VS2015 + static hdf5
  -
    matrix:
      only:
        - image: Visual Studio 2015
          HDF5_STATE: STATIC  
    init:
      - set GENERATOR="Visual Studio 14 2015%TARGET_PLATFORM%"
      - echo %GENERATOR%
    install:
      - mkdir C:\projects\fesapiEnv\dependencies
      - cd C:\projects\fesapiEnv\dependencies
      
      - appveyor DownloadFile https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.18/bin/windows/noszip/extra/hdf5-1.8.18-win64-vs2015-noszip.zip
      - 7z x hdf5-1.8.18-win64-vs2015-noszip.zip -oC:\projects\fesapiEnv\dependencies > nul 
      - msiexec.exe /i "C:\projects\fesapiEnv\dependencies\hdf5\HDF5-1.8.18-win64.msi" /qn INSTALL_ROOT=C:\projects\fesapiEnv\dependencies\hdf5-1.8.18-win64-vs2015-noszip
      
      - appveyor DownloadFile https://github.com/F2I-Consulting/Minizip/releases/download/1.1/minizip-1.1-win64-vs2015-static.zip
      - 7z x minizip-1.1-win64-vs2015-static.zip -oC:\projects\fesapiEnv\dependencies > nul
      - cd ..    
    build_script:
      - mkdir build
      - cd build
      - cmake --version
      - cmake -Wno-dev -Wno-deprecated -G %GENERATOR% ../fesapi 
            -DHDF5_USE_STATIC_LIBRARIES:BOOL=ON
            -DHDF5_ROOT=C:\projects\fesapiEnv\dependencies\hdf5-1.8.18-win64-vs2015-noszip          
            -DCMAKE_PREFIX_PATH=c:/projects/fesapiEnv/dependencies/minizip-1.1-win64-vs2015-static 
      - cmake --build . --config "%CONFIGURATION%"


#scripts to run after build
# after_build:
#   - msbuild c:\projects\fesapiEnv\fesapi\cs\fesapiCs.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
#   - cd Release
#   - copy c:\projects\fesapiEnv\dependencies\hdf5-1.8.18-win64-vs2013-noszip\bin\hdf5.dll .
#   - copy c:\projects\fesapiEnv\dependencies\hdf5-1.8.18-win64-vs2013-noszip\bin\zlib.dll .
#   - example.exe


