import fnmatch
import os
import re

# For each *.i file, this file replaces all enumerated values associated to char by the same enumerated values
# associated to int instead. 
# Enumerated values associated to char is a problem for Python generated with Swig because they
# are typed as char by Python and not as int.  
# Enumerated values associated to char are arbitrarily generated by gSOAP which we do not control

def fixFile(file):
    # replace "= '*'" with "= (int)'*'" in file
    with open (file, "r+" ) as f:
        content = f.read()
        content_new = re.sub("= \'(\w{1})\'", lambda x: "= " + str(ord(x.group(1))), content, flags = re.M)
        f.seek(0) # set the position to the top of the file
        f.write(content_new)
        f.truncate() # truncates the file        

for file in os.listdir('.'): # traverse all files in the current dir (non recursive)
    if fnmatch.fnmatch(file, '*.i'): # if the current file extension is ".i"
        fixFile(file)

